name: Trigger Azure DevOps Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DevOps Pipeline
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic ${{ secrets.AZURE_DEVOPS_PAT }}" \
            -d '{"resources": {"repositories": {"self": {"refName": "refs/heads/main"}}}}' \
            https://dev.azure.com/City-of-Helsinki/devops-toolchain/_apis/pipelines/4232/runs?api-version=6.0-preview.1
